#!/usr/bin/env python3
"""
Audit inline documentation coverage for repo-owned TypeScript, JavaScript, and Swift files.

The script enforces deterministic rules only:
- supported source files must have a top-of-file header
- selected type declarations must have a doc immediately above the declaration
- generated and vendor-owned files are excluded
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


SUPPORTED_SUFFIXES = {
    ".js": "ts",
    ".jsx": "ts",
    ".ts": "ts",
    ".tsx": "ts",
    ".swift": "swift",
}

SKIP_DIR_NAMES = {
    ".build",
    ".git",
    ".next",
    ".pnpm",
    ".turbo",
    "__tests__",
    "DerivedData",
    "Pods",
    "Tests",
    "build",
    "dist",
    "node_modules",
    "vendor",
}
SKIP_DIR_NAMES_LOWER = {name.lower() for name in SKIP_DIR_NAMES}

GENERATED_BANNER_PATTERNS = (
    re.compile(r"\bautomatically generated\b", re.IGNORECASE),
    re.compile(r"\bauto[- ]?generated\b", re.IGNORECASE),
    re.compile(r"\bgenerated file\b", re.IGNORECASE),
    re.compile(r"\bfile (?:is )?generated\b", re.IGNORECASE),
    re.compile(r"\bgenerated code\b", re.IGNORECASE),
    re.compile(r"\bcode generated\b", re.IGNORECASE),
    re.compile(r"\bdo not modify\b", re.IGNORECASE),
    re.compile(r"\bdo not edit\b", re.IGNORECASE),
    re.compile(r"@generated\b", re.IGNORECASE),
    re.compile(r"\bgenerated by\b", re.IGNORECASE),
)

NON_DOC_COMMENT_PATTERNS = (
    re.compile(r"^\s*(?:eslint|tslint|prettier|biome|oxlint|rome|stylelint|swiftlint|swiftformat)\b", re.IGNORECASE),
    re.compile(r"^\s*@(?:ts-|eslint|generated\b)", re.IGNORECASE),
    re.compile(r"^\s*(?:c8|istanbul)\s+ignore\b", re.IGNORECASE),
    re.compile(r"^\s*(?:spellchecker|cspell|codespell)\b", re.IGNORECASE),
    re.compile(r"^\s*sourceMappingURL=", re.IGNORECASE),
)

TS_TYPE_PATTERNS = [
    re.compile(
        r"^\s*(?P<prefix>(?:export\s+)?(?:default\s+)?(?:declare\s+)?(?:abstract\s+)?)class\s+(?P<name>[A-Za-z_$][\w$]*)\b"
    ),
    re.compile(
        r"^\s*(?P<prefix>(?:export\s+)?(?:declare\s+)?)interface\s+(?P<name>[A-Za-z_$][\w$]*)\b"
    ),
    re.compile(
        r"^\s*(?P<prefix>(?:export\s+)?(?:declare\s+)?)type\s+(?P<name>[A-Za-z_$][\w$]*)\b"
    ),
    re.compile(
        r"^\s*(?P<prefix>(?:export\s+)?(?:declare\s+)?(?:const\s+)?)enum\s+(?P<name>[A-Za-z_$][\w$]*)\b"
    ),
]

SWIFT_TYPE_PATTERNS = [
    re.compile(
        r"^\s*(?P<prefix>(?:(?:public|private|fileprivate|internal|open|package|final|indirect|nonisolated|distributed)\s+)*)struct\s+(?P<name>[A-Za-z_]\w*)\b"
    ),
    re.compile(
        r"^\s*(?P<prefix>(?:(?:public|private|fileprivate|internal|open|package|final|indirect|nonisolated|distributed)\s+)*)enum\s+(?P<name>[A-Za-z_]\w*)\b"
    ),
    re.compile(
        r"^\s*(?P<prefix>(?:(?:public|private|fileprivate|internal|open|package)\s+)*)protocol\s+(?P<name>[A-Za-z_]\w*)\b"
    ),
    re.compile(
        r"^\s*(?P<prefix>(?:(?:public|private|fileprivate|internal|open|package|final|nonisolated|distributed)\s+)*)actor\s+(?P<name>[A-Za-z_]\w*)\b"
    ),
    re.compile(
        r"^\s*(?P<prefix>(?:(?:public|private|fileprivate|internal|open|package|final|nonisolated|distributed)\s+)*)class\s+(?P<name>[A-Za-z_]\w*)\b"
    ),
    re.compile(
        r"^\s*(?P<prefix>(?:(?:public|private|fileprivate|internal|open|package)\s+)*)extension\s+(?P<name>[A-Za-z_]\w*)\b"
    ),
    re.compile(
        r"^\s*(?P<prefix>(?:(?:public|private|fileprivate|internal|open|package)\s+)*)typealias\s+(?P<name>[A-Za-z_]\w*)\b"
    ),
]

TYPE_PATTERNS = {
    "ts": TS_TYPE_PATTERNS,
    "swift": SWIFT_TYPE_PATTERNS,
}


@dataclass(frozen=True)
class Issue:
    path: Path
    line: int
    kind: str
    detail: str


@dataclass(frozen=True)
class TypeDeclaration:
    line_number: int
    kind: str
    name: str
    is_public_surface: bool


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Audit file headers and type docs for repo-owned TS/JS/Swift files."
    )
    parser.add_argument(
        "--fix",
        action="store_true",
        help=(
            "Apply mechanical fixes only, such as moving docs above decorators. "
            "Missing documentation content is still reported for an agent to write."
        ),
    )
    parser.add_argument(
        "--type-doc-policy",
        choices=("public", "all", "none"),
        default="public",
        help=(
            "Which type declarations require docs. "
            "'public' covers exported TS/JS and public/open/package Swift declarations. "
            "'all' covers every type declaration. 'none' checks file headers only."
        ),
    )
    parser.add_argument(
        "paths",
        nargs="*",
        default=["."],
        help="Files or directories to scan. Defaults to the current directory.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    roots = [Path(raw).resolve() for raw in args.paths]
    missing_roots = [root for root in roots if not root.exists()]
    if missing_roots:
        for root in missing_roots:
            print(f"inline-doc audit error: path does not exist: {root}", file=sys.stderr)
        return 2

    issues: list[Issue] = []
    scanned_files = 0
    fixed_files = 0

    for file_path in iter_supported_files(roots):
        scanned_files += 1
        if args.fix and fix_file(file_path, args.type_doc_policy):
            fixed_files += 1
        issues.extend(audit_file(file_path, args.type_doc_policy))

    if issues:
        print(f"inline-doc audit failed: {len(issues)} issue(s) across {scanned_files} file(s)")
        if args.fix:
            print(f"auto-fixed {fixed_files} file(s) before re-auditing")
        for issue in issues:
            print(f"{issue.path}:{issue.line}: {issue.kind}: {issue.detail}")
        return 1

    if args.fix:
        print(f"inline-doc audit passed: scanned {scanned_files} file(s), auto-fixed {fixed_files} file(s)")
        return 0

    print(f"inline-doc audit passed: scanned {scanned_files} file(s)")
    return 0


def iter_supported_files(roots: list[Path]):
    seen: set[Path] = set()
    for root in roots:
        if root.is_file():
            if is_supported_source(root) and not should_skip(root, root.parent):
                resolved = root.resolve()
                if resolved not in seen:
                    seen.add(resolved)
                    yield resolved
            continue

        for dirpath, dirnames, filenames in os.walk(root):
            dirnames[:] = [name for name in dirnames if not should_skip_dir_name(name)]
            for filename in filenames:
                path = Path(dirpath) / filename
                if not is_supported_source(path):
                    continue
                if should_skip(path, root):
                    continue
                resolved = path.resolve()
                if resolved in seen:
                    continue
                seen.add(resolved)
                yield resolved


def should_skip_dir_name(name: str) -> bool:
    return name.lower() in SKIP_DIR_NAMES_LOWER


def is_supported_source(path: Path) -> bool:
    return path.suffix in SUPPORTED_SUFFIXES


def should_skip(path: Path, scan_root: Path) -> bool:
    relative_path = path_relative_to_scan_root(path, scan_root)
    lowered_parts = {part.lower() for part in relative_path.parts}
    if lowered_parts & SKIP_DIR_NAMES_LOWER:
        return True

    name = path.name.lower()
    path_text = str(relative_path).replace("\\", "/").lower()

    if name in {"generated.ts", "generated.js", "generated.swift"}:
        return True
    if name.endswith(".d.ts"):
        return True
    if name.endswith(".spec.ts") or name.endswith(".spec.tsx"):
        return True
    if name.endswith(".test.ts") or name.endswith(".test.tsx"):
        return True
    if name.endswith(".spec.js") or name.endswith(".spec.jsx"):
        return True
    if name.endswith(".test.js") or name.endswith(".test.jsx"):
        return True
    if ".generated." in name:
        return True
    if name.endswith(".graphql.swift"):
        return True
    if "/generated/" in path_text or "/__generated__/" in path_text:
        return True
    if "/tests/" in path_text or "/test/" in path_text:
        return True
    if "/vendor/" in path_text:
        return True

    return has_generated_banner(path)


def path_relative_to_scan_root(path: Path, scan_root: Path) -> Path:
    try:
        return path.resolve().relative_to(scan_root.resolve())
    except ValueError:
        return Path(path.name)


def has_generated_banner(path: Path) -> bool:
    try:
        with path.open("r", encoding="utf-8", errors="ignore") as handle:
            banner = "".join(handle.readline() for _ in range(12)).lower()
    except OSError:
        return False

    return any(pattern.search(banner) for pattern in GENERATED_BANNER_PATTERNS)


def audit_file(path: Path, type_doc_policy: str) -> list[Issue]:
    text = read_text(path)
    language = SUPPORTED_SUFFIXES[path.suffix]
    lines = text.splitlines()
    issues: list[Issue] = []

    header_line = first_meaningful_line_index(lines)
    if header_line is None or not has_file_header(lines, header_line, language):
        issues.append(
            Issue(
                path=path,
                line=1,
                kind="missing-file-header",
                detail="expected a top-of-file header before imports or code",
            )
        )

    if type_doc_policy == "none":
        return issues

    for declaration in iter_type_declarations(lines, language):
        if not type_requires_doc(declaration, type_doc_policy):
            continue
        anchor_index = doc_anchor_index(lines, declaration.line_number - 1)
        if not has_doc_comment(lines, anchor_index):
            issues.append(
                Issue(
                    path=path,
                    line=declaration.line_number,
                    kind="missing-type-doc",
                    detail=(
                        f"{declaration.kind} `{declaration.name}` is missing a doc "
                        "immediately above the declaration"
                    ),
                )
            )

    return issues


def fix_file(path: Path, type_doc_policy: str) -> bool:
    text = read_text(path)
    language = SUPPORTED_SUFFIXES[path.suffix]
    lines = text.splitlines()
    original_text = text

    if type_doc_policy != "none":
        missing_type_docs: list[int] = []
        for declaration in iter_type_declarations(lines, language):
            if not type_requires_doc(declaration, type_doc_policy):
                continue
            anchor_index = doc_anchor_index(lines, declaration.line_number - 1)
            if not has_doc_comment(lines, anchor_index):
                missing_type_docs.append(declaration.line_number - 1)

        for declaration_index in sorted(missing_type_docs, reverse=True):
            misplaced_range = misplaced_doc_comment_range(lines, declaration_index)
            if misplaced_range is not None:
                start, end = misplaced_range
                doc_lines = lines[start : end + 1]
                del lines[start : end + 1]
                insert_index = doc_insertion_index(lines, declaration_index - len(doc_lines))
                lines[insert_index:insert_index] = doc_lines

    new_text = "\n".join(lines)
    if text.endswith("\n") or not lines:
        new_text += "\n"

    if new_text == original_text:
        return False

    path.write_text(new_text, encoding="utf-8")
    return True


def type_requires_doc(declaration: TypeDeclaration, type_doc_policy: str) -> bool:
    if type_doc_policy == "all":
        return True
    if type_doc_policy == "public":
        return declaration.is_public_surface
    return False


def read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return path.read_text(encoding="utf-8", errors="ignore")


def first_meaningful_line_index(lines: list[str]) -> int | None:
    for index, line in enumerate(lines):
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith("#!"):
            continue
        if stripped.startswith("// swift-tools-version:"):
            continue
        return index
    return None


def has_file_header(lines: list[str], start_index: int, language: str) -> bool:
    stripped = lines[start_index].strip()
    if not (stripped.startswith("//") or stripped.startswith("///") or stripped.startswith("/**") or stripped.startswith("/*")):
        return False

    end_index = comment_block_end(lines, start_index)
    if not comment_has_doc_text(lines[start_index : end_index + 1]):
        return False

    next_index = end_index + 1

    if next_index < len(lines) and lines[next_index].strip():
        return not looks_like_doc_target(lines[next_index], language)

    return True


def comment_has_doc_text(lines: Iterable[str]) -> bool:
    return any(is_doc_text_line(extract_comment_text(line)) for line in lines)


def is_doc_text_line(text: str) -> bool:
    stripped = text.strip()
    if not stripped:
        return False
    return not any(pattern.search(stripped) for pattern in NON_DOC_COMMENT_PATTERNS)


def extract_comment_text(line: str) -> str:
    stripped = line.strip()
    if stripped.startswith("/**"):
        stripped = stripped[3:]
    elif stripped.startswith("/*"):
        stripped = stripped[2:]
    elif stripped.startswith("///"):
        stripped = stripped[3:]
    elif stripped.startswith("//"):
        stripped = stripped[2:]
    elif stripped.startswith("*"):
        stripped = stripped[1:]

    if stripped.endswith("*/"):
        stripped = stripped[:-2]

    return stripped.strip()


def comment_block_end(lines: list[str], start_index: int) -> int:
    stripped = lines[start_index].strip()
    if stripped.startswith("/**") or stripped.startswith("/*"):
        cursor = start_index
        while cursor < len(lines):
            if lines[cursor].strip().endswith("*/"):
                return cursor
            cursor += 1
        return start_index

    cursor = start_index
    while cursor + 1 < len(lines):
        next_stripped = lines[cursor + 1].strip()
        if next_stripped.startswith("//") or next_stripped.startswith("///"):
            cursor += 1
            continue
        break
    return cursor


def looks_like_doc_target(line: str, language: str) -> bool:
    stripped = line.strip()
    if stripped.startswith("@"):
        return True
    return any(pattern.match(line) for pattern in TYPE_PATTERNS[language])


def iter_type_declarations(lines: list[str], language: str):
    patterns = TYPE_PATTERNS[language]
    in_ts_import_block = False

    for index, line in enumerate(lines):
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith("//") or stripped.startswith("/*") or stripped.startswith("*"):
            continue
        if language == "ts":
            if in_ts_import_block:
                if " from " in stripped or stripped.endswith(";"):
                    in_ts_import_block = False
                continue

            if stripped.startswith("import "):
                if " from " not in stripped and not stripped.endswith(";"):
                    in_ts_import_block = True
                continue

            if stripped.startswith("export {") or stripped.startswith("export *"):
                continue

        for pattern in patterns:
            match = pattern.match(declaration_scan_line(line, language))
            if not match:
                continue

            keyword = declaration_keyword_from_pattern(pattern.pattern)
            name = match.group("name")
            if language == "swift" and name in {"func", "var", "let", "subscript", "init"}:
                continue
            yield TypeDeclaration(
                line_number=index + 1,
                kind=keyword,
                name=name,
                is_public_surface=is_public_surface(language, match.group("prefix")),
            )
            break


def declaration_scan_line(line: str, language: str) -> str:
    if language != "swift":
        return line
    return re.sub(r"^\s*(?:@[A-Za-z_]\w*(?:\([^)]*\))?\s+)+", "", line)


def is_public_surface(language: str, prefix: str) -> bool:
    words = set(prefix.split())
    if language == "ts":
        return "export" in words
    return bool(words & {"public", "open", "package"})


def declaration_keyword_from_pattern(pattern: str) -> str:
    for keyword in (
        "class",
        "interface",
        "type",
        "enum",
        "struct",
        "protocol",
        "actor",
        "extension",
        "typealias",
    ):
        if keyword in pattern:
            return keyword
    return "type"


def doc_anchor_index(lines: list[str], declaration_index: int) -> int:
    decorator_start = decorator_block_start(lines, declaration_index)
    if decorator_start is not None:
        return decorator_start - 1

    cursor = declaration_index - 1
    while cursor >= 0:
        stripped = lines[cursor].strip()
        if not stripped:
            break
        if stripped.startswith("@"):
            cursor -= 1
            continue
        break
    return cursor


def doc_insertion_index(lines: list[str], declaration_index: int) -> int:
    decorator_start = decorator_block_start(lines, declaration_index)
    if decorator_start is not None:
        return decorator_start

    cursor = declaration_index
    while cursor > 0:
        stripped = lines[cursor - 1].strip()
        if not stripped:
            break
        if stripped.startswith("@"):
            cursor -= 1
            continue
        break
    return cursor


def decorator_block_start(lines: list[str], declaration_index: int) -> int | None:
    cursor = declaration_index - 1
    comment_range = doc_comment_range_ending_at(lines, cursor)
    if comment_range is not None and comment_has_doc_text(lines[comment_range[0] : comment_range[1] + 1]):
        cursor = comment_range[0] - 1

    candidate: int | None = None
    while cursor >= 0:
        stripped = lines[cursor].strip()
        if not stripped:
            break
        if stripped.startswith("@"):
            candidate = cursor
        cursor -= 1
    return candidate


def has_doc_comment(lines: list[str], index: int) -> bool:
    if index < 0:
        return False

    stripped = lines[index].strip()
    if stripped.startswith("//") or stripped.startswith("///"):
        comment_range = doc_comment_range_ending_at(lines, index)
        return comment_range is not None and comment_has_doc_text(lines[comment_range[0] : comment_range[1] + 1])

    if stripped.endswith("*/"):
        comment_range = doc_comment_range_ending_at(lines, index)
        return comment_range is not None and comment_has_doc_text(lines[comment_range[0] : comment_range[1] + 1])

    return False


def misplaced_doc_comment_range(lines: list[str], declaration_index: int) -> tuple[int, int] | None:
    decorator_start = decorator_block_start(lines, declaration_index)
    if decorator_start is None:
        return None

    return doc_comment_range_ending_at(lines, declaration_index - 1)


def doc_comment_range_ending_at(lines: list[str], end_index: int) -> tuple[int, int] | None:
    if end_index < 0:
        return None

    stripped = lines[end_index].strip()
    if stripped.startswith("///") or stripped.startswith("//"):
        start = end_index
        while start > 0:
            previous = lines[start - 1].strip()
            if previous.startswith("///") or previous.startswith("//"):
                start -= 1
                continue
            break
        return start, end_index

    if stripped.endswith("*/"):
        if stripped.startswith("/**") or stripped.startswith("/*"):
            return end_index, end_index

        cursor = end_index - 1
        while cursor >= 0:
            current = lines[cursor].strip()
            if current.startswith("/**") or current.startswith("/*"):
                return cursor, end_index
            if current.startswith("*"):
                cursor -= 1
                continue
            return None

    return None


if __name__ == "__main__":
    sys.exit(main())
